#version: "3"
services:
  ocean-cgi:
    restart: unless-stopped
    container_name: ocean-cgi
    build: ./docker_file
    ports:
      - "8088:80"
    volumes:
      - /mnt/data/ocean_portal/config/oceanPlotter/cgi-bin:/usr/lib/cgi-bin
      - /mnt/data/ocean_portal/config/oceanPlotter/docker_file/apache2.conf:/etc/apache2/apache2.conf
